[package]
name = "dognut"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.*"
crossterm = "0.*"

tobj = "3.*"
cfg-if = "1"
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
env_logger = "0.9"
log = "0.4"
pollster = "0.2"
wgpu = "0.*"
winit = "0.*"

tokio = {version="1", features=["full"]}

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[[bin]]
name = "test"
