// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netpacket.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:proto.net_packet.NetPacket)
pub struct NetPacket {
    // message fields
    // @@protoc_insertion_point(field:proto.net_packet.NetPacket.kind)
    pub kind: ::protobuf::EnumOrUnknown<PacketKind>,
    // @@protoc_insertion_point(field:proto.net_packet.NetPacket.data)
    pub data: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:proto.net_packet.NetPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NetPacket {
    fn default() -> &'a NetPacket {
        <NetPacket as ::protobuf::Message>::default_instance()
    }
}

impl NetPacket {
    pub fn new() -> NetPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "kind",
            |m: &NetPacket| { &m.kind },
            |m: &mut NetPacket| { &mut m.kind },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &NetPacket| { &m.data },
            |m: &mut NetPacket| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NetPacket>(
            "NetPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NetPacket {
    const NAME: &'static str = "NetPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.kind = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.data = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.kind != ::protobuf::EnumOrUnknown::new(PacketKind::VideoPacket) {
            my_size += ::protobuf::rt::int32_size(1, self.kind.value());
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.kind != ::protobuf::EnumOrUnknown::new(PacketKind::VideoPacket) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.kind))?;
        }
        if !self.data.is_empty() {
            os.write_bytes(2, &self.data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NetPacket {
        NetPacket::new()
    }

    fn clear(&mut self) {
        self.kind = ::protobuf::EnumOrUnknown::new(PacketKind::VideoPacket);
        self.data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NetPacket {
        static instance: NetPacket = NetPacket {
            kind: ::protobuf::EnumOrUnknown::from_i32(0),
            data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NetPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NetPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NetPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NetPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:proto.net_packet.PacketKind)
pub enum PacketKind {
    // @@protoc_insertion_point(enum_value:proto.net_packet.PacketKind.VideoPacket)
    VideoPacket = 0,
}

impl ::protobuf::Enum for PacketKind {
    const NAME: &'static str = "PacketKind";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<PacketKind> {
        match value {
            0 => ::std::option::Option::Some(PacketKind::VideoPacket),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [PacketKind] = &[
        PacketKind::VideoPacket,
    ];
}

impl ::protobuf::EnumFull for PacketKind {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("PacketKind").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for PacketKind {
    fn default() -> Self {
        PacketKind::VideoPacket
    }
}

impl PacketKind {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<PacketKind>("PacketKind")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0fnetpacket.proto\x12\x10proto.net_packet\"Q\n\tNetPacket\x120\n\x04\
    kind\x18\x01\x20\x01(\x0e2\x1c.proto.net_packet.PacketKindR\x04kind\x12\
    \x12\n\x04data\x18\x02\x20\x01(\x0cR\x04data*\x1d\n\nPacketKind\x12\x0f\
    \n\x0bVideoPacket\x10\0J\xe3\x01\n\x06\x12\x04\0\0\x0c\x01\n\x08\n\x01\
    \x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x01\0\x19\n\n\n\x02\x05\0\
    \x12\x04\x04\0\x06\x01\n\n\n\x03\x05\0\x01\x12\x03\x04\x05\x0f\n\x0b\n\
    \x04\x05\0\x02\0\x12\x03\x05\x02\x12\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03\
    \x05\x02\r\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x05\x10\x11\n\n\n\x02\x04\
    \0\x12\x04\t\0\x0c\x01\n\n\n\x03\x04\0\x01\x12\x03\t\x08\x11\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\n\x02\x16\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\n\x02\
    \x0c\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\n\r\x11\n\x0c\n\x05\x04\0\x02\0\
    \x03\x12\x03\n\x14\x15\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x0b\x02\x11\n\
    \x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x0b\x02\x07\n\x0c\n\x05\x04\0\x02\
    \x01\x01\x12\x03\x0b\x08\x0c\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x0b\
    \x0f\x10b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(NetPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(PacketKind::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
